name: CI

on:
  push:
  pull_request:

jobs:
  build-cross-live-ci:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
     - name: prepare
       uses: actions/checkout@v4

     - name: build an image and test ssh on NetBSD on emulator
       uses: ./
       with:
         machine: "vax"
         release: "10.1"

         prepare: |
           PKG_PATH=https://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r)/All
           pkg_add -uv tcsh

         configure: |
           pwd

         build: |
           uname -a
           sysctl hw.model
           ls -lR /home/runner
